# Generated by Django 2.1.1 on 2020-05-20 18:02

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lng', models.DecimalField(decimal_places=16, max_digits=22)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.IntegerField(help_text='Duration for new lease in months', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('earliest_move_in', models.DateField(default=datetime.datetime.now)),
                ('latest_move_out', models.DateField(default=datetime.datetime.now)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
