# Generated by Django 2.1.1 on 2020-05-22 04:19

from django.db import migrations, models
import django.db.models.deletion
import rental.models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=rental.models.upload_image_path)),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='featured_image',
            field=models.ImageField(default='default-listing.jpg', upload_to=rental.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='image',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.House'),
        ),
    ]
