# Generated by Django 2.1.1 on 2020-05-22 07:43

from django.db import migrations, models
import rental.models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20200521_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to=rental.models.upload_image_path, verbose_name='Image'),
        ),
    ]
