# Generated by Django 2.1.1 on 2020-07-28 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20200721_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration for new lease in months', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
