# Generated by Django 2.1.1 on 2020-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20201127_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqvapplication',
            name='num_people_coming',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sqvapplication',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
