# Generated by Django 2.1.1 on 2020-11-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20201127_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqvapplication',
            name='notes',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
