# Generated by Django 2.1.1 on 2020-08-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_imagelinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelinks',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
