# Generated by Django 2.1.1 on 2020-11-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rentals', '0005_sqvapplication_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SqvAppAvail',
            new_name='SfvAppAvail',
        ),
        migrations.RenameModel(
            old_name='SqvApplication',
            new_name='SfvApplication',
        ),
        migrations.RenameField(
            model_name='sfvappavail',
            old_name='sqv_application',
            new_name='sfv_application',
        ),
    ]
