# Generated by Django 2.1.1 on 2020-11-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_auto_20201127_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfvappavail',
            name='sfv_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.SfvApplication'),
        ),
    ]
