# Generated by Django 2.1.1 on 2020-11-28 20:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_auto_20201127_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sfv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(default='', max_length=5000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='sfvappavail',
            name='availalbe',
        ),
        migrations.RemoveField(
            model_name='sfvappavail',
            name='day',
        ),
        migrations.RemoveField(
            model_name='sfvapplication',
            name='num_people_coming',
        ),
        migrations.AddField(
            model_name='sfvappavail',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sfv',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='rentals.SfvApplication'),
        ),
    ]
