# Generated by Django 2.1.1 on 2020-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_auto_20201128_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfv',
            name='application',
        ),
        migrations.AddField(
            model_name='sfvappavail',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Sfv',
        ),
    ]
