# Generated by Django 2.1.1 on 2020-11-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_auto_20201129_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfvappavail',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
