# Generated by Django 2.1.5 on 2021-02-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_auto_20210201_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='count',
            new_name='amount',
        ),
    ]
