# Generated by Django 2.1.5 on 2021-02-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_auto_20210201_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
