# Generated by Django 2.1.1 on 2020-12-21 17:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone Number must be without +', regex='\\d{9,13}$')])),
                ('business_mobile_number_verified', models.BooleanField(default=False)),
                ('business_description', models.CharField(blank=True, help_text='Describe about yourself in short', max_length=400)),
                ('business_address', models.CharField(max_length=100)),
                ('verification_doc', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1200, 1200], upload_to='verifications')),
                ('verified', models.IntegerField(choices=[(1, 'Not Verified'), (2, 'Processing'), (3, 'Verified')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
