# Generated by Django 2.1.1 on 2021-01-04 19:48

import deliveranything.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_auto_20201213_0608'),
        ('accounts', '0014_auto_20201219_1018'),
        ('deliveranything', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True)),
                ('business_city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('pickup', models.CharField(blank=True, max_length=100)),
                ('dropoff', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField(blank=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('length', models.IntegerField(blank=True)),
                ('width', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('quote', models.IntegerField(blank=True, null=True)),
                ('deliverer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Tasker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveranything.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers_licence_number', models.CharField(max_length=50)),
                ('make', models.CharField(help_text='(e.g. Ford)', max_length=50)),
                ('model', models.CharField(help_text='(e.g. Focus)', max_length=50)),
                ('year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), deliveranything.models.year_choices])),
                ('color', models.CharField(max_length=50)),
                ('registration', models.CharField(max_length=50)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Tasker')),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_mobile_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_mobile_number_verified',
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(default='Default Business Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deliveranything.Business'),
        ),
        migrations.AddField(
            model_name='address',
            name='business_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Country'),
        ),
    ]
