# Generated by Django 2.1.1 on 2020-12-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201219_1018'),
        ('deliveranything', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_address',
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(default='poggs', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='business_description',
            field=models.CharField(blank=True, help_text='Describe your business in short', max_length=400),
        ),
        migrations.AddField(
            model_name='address',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deliveranything.Business'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Country'),
        ),
    ]
