# Generated by Django 2.1.1 on 2020-12-21 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0002_auto_20201221_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_mobile_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Phone Number must be without +', regex='\\d{9,13}$')]),
        ),
    ]
