# Generated by Django 2.1.1 on 2020-12-27 00:00

import deliveranything.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0002_auto_20201226_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), deliveranything.models.year_choices]),
        ),
    ]
