# Generated by Django 2.1.5 on 2021-01-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0003_auto_20210109_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='wait_time',
            field=models.CharField(choices=[('0', 'None'), ('5', '5 Minutes'), ('10', '10 Minutes'), ('15', '15 Minutes'), ('20', '20 Minutes'), ('25', '25 Minutes'), ('30', '30 Minutes'), ('30+', '30+ Minutes')], max_length=12),
        ),
    ]
