# Generated by Django 2.1.1 on 2020-12-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0003_auto_20201226_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='quote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
