# Generated by Django 2.1.1 on 2020-12-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0003_auto_20201221_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='business_country',
        ),
    ]
