# Generated by Django 2.1.1 on 2020-12-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0004_auto_20201221_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_mobile_number',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_mobile_number_verified',
        ),
    ]
