# Generated by Django 2.1.5 on 2021-01-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0005_delivery_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
