# Generated by Django 2.1.5 on 2021-01-18 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201213_0608'),
        ('deliveranything', '0006_auto_20210111_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('pickup', models.CharField(blank=True, max_length=100)),
                ('dropoff', models.CharField(blank=True, max_length=100)),
                ('time', models.DateTimeField(blank=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('wait_time', models.CharField(choices=[('0', 'None'), ('5', '5 Minutes'), ('10', '10 Minutes'), ('15', '15 Minutes'), ('20', '20 Minutes'), ('25', '25 Minutes'), ('30', '30 Minutes'), ('30+', '30+ Minutes')], max_length=12)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, help_text='Pounds (lbs)')),
                ('quote', models.IntegerField(blank=True, null=True)),
                ('deliverer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Tasker')),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousDeliveryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveranything.AnonymousDelivery')),
            ],
        ),
    ]
