# Generated by Django 2.1.1 on 2020-12-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0006_auto_20201221_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=7),
        ),
    ]
