# Generated by Django 2.1.5 on 2021-01-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0007_anonymousdelivery_anonymousdeliveryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousdelivery',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Pounds (lbs)', null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Pounds (lbs)', null=True),
        ),
    ]
