# Generated by Django 2.1.5 on 2021-01-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0008_auto_20210118_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='intent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
