# Generated by Django 2.1.5 on 2021-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0009_delivery_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousdelivery',
            name='quote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
