# Generated by Django 2.1.5 on 2021-01-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveranything', '0010_auto_20210123_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousdelivery',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anonymousdelivery',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
