# Generated by Django 2.1.1 on 2020-10-22 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner', django_resized.forms.ResizedImageField(crop=None, default='default-profile.jpg', force_format='PNG', keep_meta=True, quality=0, size=[640, 480], upload_to='services')),
                ('description', models.CharField(max_length=500)),
                ('average_project_budget', models.CharField(help_text='Ex $35-$75', max_length=20)),
                ('favourite', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('notes', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tasker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_doc', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=0, size=[1200, 1200], upload_to='verifications')),
                ('verified', models.IntegerField(choices=[(1, 'Not Verified'), (2, 'Processing'), (3, 'Verified')], default=1)),
                ('services', models.IntegerField(choices=[(0, 'None'), (1, 'Cleaning'), (2, 'Construction'), (3, 'Decoration'), (4, 'Delivery'), (5, 'Electrician'), (6, 'Furniture Removal'), (7, 'Interior Designing'), (8, 'Moving Help'), (9, 'Heavy & Minor lifting'), (10, 'Heavy & Minor lifting')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
