# Generated by Django 2.1.1 on 2020-08-19 19:05

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner', django_resized.forms.ResizedImageField(crop=None, default='default-profile.jpg', force_format='PNG', keep_meta=True, quality=0, size=[640, 480], upload_to='services')),
                ('description', models.CharField(max_length=500)),
                ('average_project_budget', models.CharField(help_text='Ex $35-$75', max_length=20)),
                ('favourite', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('date', models.DateTimeField(null=True)),
                ('notes', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=20)),
            ],
        ),
    ]
