# Generated by Django 2.1.1 on 2020-09-20 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_doc', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=0, size=[1200, 1200], upload_to='verifications')),
                ('verified', models.IntegerField(choices=[(1, 'Not Verified'), (2, 'Processing'), (3, 'Verified')], default=1)),
                ('services', models.IntegerField(choices=[(0, 'None'), (1, 'Cleaning'), (2, 'Construction'), (3, 'Decoration'), (4, 'Delivery'), (5, 'Electrician'), (6, 'Furniture Removal'), (7, 'Interior Designing'), (8, 'Moving Help'), (9, 'Heavy & Minor lifting'), (10, 'Heavy & Minor lifting')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
