# Generated by Django 2.1.1 on 2020-12-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201210_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskday',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasktimeslot',
            name='day',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='update_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceCustomer',
        ),
        migrations.DeleteModel(
            name='TaskDay',
        ),
        migrations.DeleteModel(
            name='TaskTimeSlot',
        ),
    ]
