# Generated by Django 2.1.1 on 2020-12-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='country_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
