# Generated by Django 2.1.1 on 2020-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default-profile.jpg', upload_to='profile_pics'),
        ),
    ]
