# Generated by Django 2.1.1 on 2020-06-14 04:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200613_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_doc',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=0, size=[1200, 1200], upload_to='verifications'),
        ),
    ]
