# Generated by Django 2.1.1 on 2020-07-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200727_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('reason', models.IntegerField(choices=[(1, 'Finding a rental'), (2, 'Listing a rental'), (3, 'Screening application'), (4, 'Applying for rentals'), (5, 'Rent collection and payments'), (6, 'Account details'), (7, 'General information'), (8, 'Account activation'), (9, 'Other')])),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.IntegerField(choices=[(1, 'Not Verified'), (2, 'Processing'), (3, 'Verified')], default=1),
        ),
    ]
