# Generated by Django 2.1.1 on 2020-06-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200608_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(default='default-profile.jpg', upload_to='profile_pics'),
        ),
    ]
