# Generated by Django 2.1.1 on 2020-06-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200608_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pro_pic',
            new_name='profile_pic',
        ),
    ]
