# Generated by Django 2.1.1 on 2020-06-09 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200608_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone Number must be without +', regex='\\d{9,13}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number_varified',
            field=models.BooleanField(default=False),
        ),
    ]
