# Generated by Django 2.1.1 on 2020-12-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201213_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='category',
            field=models.IntegerField(choices=[(1, 'Basement'), (2, '1 Bedroom'), (3, '2 Bedroom'), (4, 'Condo'), (5, 'Townhouse'), (6, 'Co-Living'), (7, 'Other')], default=1),
        ),
        migrations.AddField(
            model_name='datalist',
            name='location',
            field=models.IntegerField(choices=[(1, 'North Vancouver'), (2, 'West Vancouver'), (3, 'East Vancouver'), (4, 'South Vancouver'), (5, 'Downtown Vancouver'), (6, 'Burnaby'), (7, 'Surrey'), (8, 'Richmond'), (9, 'Abbotsford'), (10, 'Langley')], default=1),
        ),
        migrations.AddField(
            model_name='datalist',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datalist',
            name='type',
            field=models.IntegerField(choices=[(1, 'Daily'), (2, 'Monthly')], default=1),
        ),
    ]
