# Generated by Django 2.1.1 on 2020-12-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201214_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='price',
            field=models.CharField(max_length=25),
        ),
    ]
