# Generated by Django 2.1.1 on 2020-12-14 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201214_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred_users',
            field=models.ManyToManyField(related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
