# Generated by Django 2.1.1 on 2020-12-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201214_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataList',
            new_name='ListingDataList',
        ),
    ]
