# Generated by Django 2.1.1 on 2020-12-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201219_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookingDataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=14)),
                ('text', models.TextField(max_length=250)),
            ],
        ),
    ]
