# Generated by Django 2.1.1 on 2020-12-19 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_lookingdatalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referred_users',
            field=models.ManyToManyField(blank=True, related_name='referred_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
