# Generated by Django 2.1.5 on 2021-01-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201219_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
