# Generated by Django 2.1.1 on 2020-06-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Landlord', 'landlord'), ('Lease Holder', 'lease'), ('Free', 'free')], default='Free', max_length=30),
        ),
    ]
