# Generated by Django 2.1.1 on 2020-12-01 23:15

import buyandsell.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(default='default-profile.jpg', upload_to='category_pics/buyandsell')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_price', models.PositiveIntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyandsell_applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Excellent', 'Excellent'), ('New', 'New')], default='Good', max_length=15)),
                ('amount', models.IntegerField(default=1)),
                ('applications', models.ManyToManyField(blank=True, related_name='buyandsell_applications', to='buyandsell.Offer')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyandsell_posting_area', to='accounts.Area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyandsell.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyandsell_posting_city', to='accounts.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyandsell_posting_country', to='accounts.Country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyandsell_posting_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=buyandsell.models.upload_image_path, verbose_name='BuyandSellImage')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyandsell.Posting')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyandsell_offer_posting', to='buyandsell.Posting'),
        ),
    ]
