# Generated by Django 2.1.5 on 2020-11-28 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20201128_1057'),
        ('buyandsell', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Posting',
        ),
        migrations.RenameModel(
            old_name='ListingImage',
            new_name='PostingImage',
        ),
    ]
