# Generated by Django 2.1.5 on 2020-11-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0002_auto_20201128_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='listing',
        ),
        migrations.AddField(
            model_name='offer',
            name='posting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyandsell_offer_posting', to='buyandsell.Posting'),
            preserve_default=False,
        ),
    ]
