# Generated by Django 2.1.5 on 2020-11-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyandsell', '0004_offer_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postingimage',
            old_name='listing',
            new_name='posting',
        ),
    ]
