from decouple import config


if config('DEBUG'):
    STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY_DEBUG')
    STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY_DEBUG')

else:
    STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY_PROD')
    STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY_PROD')