# Generated by Django 2.1.1 on 2020-06-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('Home', 'home'), ('Basement', 'basement'), ('Condo', 'Condo'), ('Duplex', 'duplex'), ('Room', 'room'), ('Townhouse', 'townhouse'), ('Other', 'other')], max_length=10)),
                ('province', models.CharField(choices=[('Newfoundland and Labrador', 'NL'), ('Prince Edward Island', 'PE'), ('Nova Scotia', 'NS'), ('New Brunswick', 'NB'), ('Quebec', 'QC'), ('Ontario', 'ON'), ('Manitoba', 'MB'), ('Saskatchewan', 'SK'), ('Alberta', 'AB'), ('British Columbia', 'BC'), ('Yukon', 'YT'), ('Northwest Territories', 'NT'), ('Nunavut', 'NU')], max_length=10)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
