# Generated by Django 2.1.1 on 2020-06-02 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='improvements',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Yes with landlords consent')], default=2),
        ),
        migrations.AddField(
            model_name='agreement',
            name='landlord_phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone Number must be without +, and all digits', regex='\\d{9,13}$')]),
        ),
        migrations.AddField(
            model_name='agreement',
            name='landlord_type',
            field=models.IntegerField(choices=[(1, 'Individual'), (2, 'Corporation/Organization')], default=1),
        ),
        migrations.AddField(
            model_name='agreement',
            name='lease_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='lease_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='lease_type',
            field=models.IntegerField(choices=[(1, 'Fixed term'), (2, 'Month to month basis')], default=2),
        ),
        migrations.AddField(
            model_name='agreement',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='maintenance_cost',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='agreement',
            name='monthly_rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agreement',
            name='other_occupants_allowed',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='agreement',
            name='parking_access',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='agreement',
            name='pets_allowed',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='agreement',
            name='renew',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='agreement',
            name='smoking_allowed',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='agreement',
            name='sublease',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant_phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone Number must be without +, and all digits', regex='\\d{9,13}$')]),
        ),
        migrations.AddField(
            model_name='agreement',
            name='utility_cost',
            field=models.IntegerField(choices=[(1, 'Tenant pays for all utilities'), (2, 'Utilities included in cost of rent'), (3, 'shared')], default=1),
        ),
        migrations.AddField(
            model_name='agreement',
            name='vaping_allowed',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='property_type',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'Basement'), (3, 'Condo'), (4, 'Duplex'), (5, 'Room'), (6, 'Townhouse'), (7, 'Other')]),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='province',
            field=models.CharField(choices=[('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut')], max_length=10),
        ),
    ]
