# Generated by Django 2.1.1 on 2020-06-02 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20200602_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
