# Generated by Django 2.1.1 on 2020-06-02 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_agreement_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='tenants_email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
