# Generated by Django 2.1.1 on 2020-06-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_agreement_tenants_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='tenant_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
