# Generated by Django 2.1.1 on 2020-06-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_agreement_tenant_agreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_created',
            field=models.DateField(auto_now=True),
        ),
    ]
