# Generated by Django 2.1.1 on 2020-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0006_agreement_agreement_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='tenant_agreed',
        ),
        migrations.AddField(
            model_name='agreement',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Active'), (3, 'Inactive')], default=1),
        ),
    ]
