# Generated by Django 2.1.1 on 2020-06-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_auto_20200610_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='tenants_email',
            field=models.EmailField(max_length=100),
        ),
    ]
