# Generated by Django 2.1.1 on 2020-06-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0009_agreement_signed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='security_deposit',
            field=models.IntegerField(default=0),
        ),
    ]
