# Generated by Django 2.1.1 on 2020-06-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
