# Generated by Django 2.1.1 on 2020-06-14 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
