# Generated by Django 2.1.1 on 2020-06-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='resign',
            field=models.BooleanField(default=False, help_text='When the sublease ends you can sign a new lease directly with the landlord', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='uploaded_at',
            field=models.DateField(auto_now=True),
        ),
    ]
