# Generated by Django 2.1.1 on 2020-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_auto_20200627_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='link',
            field=models.CharField(max_length=350),
        ),
    ]
