# Generated by Django 2.1.1 on 2020-06-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_auto_20200607_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='house',
            name='lng',
        ),
    ]
