# Generated by Django 2.1.1 on 2020-06-09 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_auto_20200607_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
