# Generated by Django 2.1.1 on 2020-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_auto_20200702_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='external_source',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
