# Generated by Django 2.1.1 on 2020-06-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_house_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='province',
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.IntegerField(choices=[(1, 'Vancouver'), (2, 'Toronto'), (3, 'Seattle'), (4, 'New York')], help_text='Currently we are limited to these cities', null=True),
        ),
    ]
