# Generated by Django 2.1.1 on 2020-06-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_auto_20200609_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rental_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Using Us'), (2, 'Other Platform')], null=True),
        ),
    ]
