# Generated by Django 2.1.1 on 2020-07-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_auto_20200714_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateField(),
        ),
    ]
