# Generated by Django 2.1.1 on 2020-06-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_house_rental_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='state',
        ),
        migrations.AddField(
            model_name='house',
            name='province',
            field=models.CharField(choices=[('BC', 'British Columbia')], help_text='Currently we are limited to these provinces', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.IntegerField(choices=[(1, 'Vancouver'), (2, 'Burnaby'), (3, 'Richmond'), (4, 'Coquitlam'), (5, 'New Westminster'), (6, 'Surrey')], help_text='Currently we are limited to these cities', null=True),
        ),
    ]
