# Generated by Django 2.1.1 on 2020-06-13 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leases', '0006_auto_20200612_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
