# Generated by Django 2.1.1 on 2020-12-02 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone Number must be without +', regex='\\d{9,13}$')]),
        ),
    ]
